Computer_Model/Models/ComputerModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Computer_Model.Models
{
    [Table("Computers")]
    public class ComputerModel
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Computer_ID { get; set; }

        public string Computer_Name { get; set; }

        public string Computer_Price { get; set; }

        public DateTime Document_Date { get; set; }

        public string OS { get; set; }
    }
}

Computer_Model/Models/Database.cs
 using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace Computer_Model.Models
{
    public class Database : DbContext
    {
        public Database() : base("MyDB")
        { 
            
        }
        public DbSet<ComputerModel> Computers { get; set; }
    }
}

Computer_Model/Controllers/ComputerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Computer_Model.Models;

namespace Computer_Model.Controllers
{
    public class ComputerController : Controller
    {
        readonly Database db = new Database();
        // GET: Computer
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult ViewAll()
        {
            

           

            //ComputerModel model = new ComputerModel();
            //model.Computer_Name = "Acer Nitro";
            //model.Computer_Price = "44000";
            //model.Document_Date = DateTime.Now;
            //model.OS = "Windows";
            //List<ComputerModel> comp = new List<ComputerModel>();
            //comp.Add(model);
            return View(db.Computers.ToList());
        }
    }
}

Computer_Model/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Computer_Model.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

Computer_Model/Views/Computer/ViewAll.cshtml
@model  List<Computer_Model.Models.ComputerModel>
@using Computer_Model.Models;
@{
    ViewBag.Title = "ViewAll";
    int Index = 1;
}


<table class="table table-bordered" style="margin-top:30px;">
    <thead>
        <tr>
            <th>SR No.</th>
            <th>Name</th>
            <th>Price</th>
            <th>Date</th>
            <th>OS</th>
        </tr>
    </thead>
    @foreach (ComputerModel computer in Model.ToList())
    {
            <tr>
                <td>@Index</td>
                <td>@computer.Computer_Name</td>
                <td>@computer.Computer_Price</td>
                <td>@computer.Document_Date.ToString("dd/MM/yyyy")</td>
                <td>@computer.OS</td>
            </tr>
        Index++;
    }
    <tfoot>
        <tr>
            <th colspan="2">Total :</th>
            <th>@Model.ToList().Sum(m => m.Computer_Price)</th>
        </tr>
    </tfoot>
    </table>

Computer_Model/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

Computer_Model/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Computer_Model/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

Computer_Model/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("View Computers", "ViewAll", "Computer")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>